buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '6.+', changing: true
    }
}

plugins {
    id 'eclipse'
    id 'maven-publish'
}

apply plugin: 'net.minecraftforge.gradle'

version = '1.0.0'
group = 'com.jagtaczarmor'
archivesBaseName = 'jagtaczarmor'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', 'jagtaczarmor'
            mods {
                jagtaczarmor {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', 'jagtaczarmor'
            mods {
                jagtaczarmor {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            args '--mod', 'jagtaczarmor', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
            mods {
                jagtaczarmor {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.3.0'

    // GeckoLib 4.8.4 - как обычная зависимость
    implementation name: 'geckolib-forge-1.20.1-4.8.4'

    // JEI 15.56.0.204 - как обычная зависимость
    compileOnly name: 'jei-1.20.1-forge-15.56.0.204'
    runtimeOnly name: 'jei-1.20.1-forge-15.56.0.204'

    // TACZ 1.1.8-hotfix - как обычная зависимость
    implementation name: 'tacz-1.20.1-1.1.8-hotfix'
}

jar {
    manifest {
        attributes([
                "Specification-Title": "jagtaczarmor",
                "Specification-Vendor": "jagtaczarmor",
                "Specification-Version": "1",
                "Implementation-Title": project.name,
                "Implementation-Version": "${version}",
                "Implementation-Vendor" :"jagtaczarmor",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

jar.finalizedBy('reobfJar')

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}